<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/Commands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd

# Define the student data
student_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Age': [20, 21, 19, 22, 20, 23, 21],
    'University': ['MIT', 'Stanford', 'Harvard', 'Yale', 'Princeton', 'Columbia', 'Duke']
}
df_students = pd.DataFrame(student_data)
output_path = '/content/data.csv'
df_students.to_csv(output_path, index=False)

print(f"Successfully created '{output_path}' with student records.")
display(df_students.head())

Successfully created '/content/data.csv' with student records.

      Name  Age University
0    Alice   20        MIT
1      Bob   21   Stanford
2  Charlie   19    Harvard
3    David   22       Yale
4      Eve   20  Princeton

In [45]:
student_data['City'] = ['Iris','Tokoyo','London','Spain','Paris','Berlin','Rome']
df_student = pd.DataFrame(student_data)
display(df_student)

      Name  Age University    City
0    Alice   20        MIT    Iris
1      Bob   21   Stanford  Tokoyo
2  Charlie   19    Harvard  London
3    David   22       Yale   Spain
4      Eve   20  Princeton   Paris
5    Frank   23   Columbia  Berlin
6    Grace   21       Duke    Rome

In [46]:
df_student.columns = ['NAME','AGE','UNIVERSITY','CITY']
display(df_student)

      NAME  AGE UNIVERSITY    CITY
0    Alice   20        MIT    Iris
1      Bob   21   Stanford  Tokoyo
2  Charlie   19    Harvard  London
3    David   22       Yale   Spain
4      Eve   20  Princeton   Paris
5    Frank   23   Columbia  Berlin
6    Grace   21       Duke    Rome

In [47]:
df_student.drop(['AGE'],axis=1, inplace = True)
display(df_student)

      NAME UNIVERSITY    CITY
0    Alice        MIT    Iris
1      Bob   Stanford  Tokoyo
2  Charlie    Harvard  London
3    David       Yale   Spain
4      Eve  Princeton   Paris
5    Frank   Columbia  Berlin
6    Grace       Duke    Rome

In [48]:
df_student['MARKS'] = [201, 202, 304, 403, 205, 304, 202]
df_student.head()
df_student['AVG_MARKS'] = df_student['MARKS'].apply(lambda x:x/5)
df_student.head()

      NAME UNIVERSITY    CITY  MARKS  AVG_MARKS
0    Alice        MIT    Iris    201       40.2
1      Bob   Stanford  Tokoyo    202       40.4
2  Charlie    Harvard  London    304       60.8
3    David       Yale   Spain    403       80.6
4      Eve  Princeton   Paris    205       41.0

In [49]:
df_student.index = [10, 17, 14, 33, 12, 34, 22]
df_student.head()

       NAME UNIVERSITY    CITY  MARKS  AVG_MARKS
10    Alice        MIT    Iris    201       40.2
17      Bob   Stanford  Tokoyo    202       40.4
14  Charlie    Harvard  London    304       60.8
33    David       Yale   Spain    403       80.6
12      Eve  Princeton   Paris    205       41.0

In [50]:
df_student.sort_index()
#df_student.sort_index(ascending=False)
df_student.head()

       NAME UNIVERSITY    CITY  MARKS  AVG_MARKS
10    Alice        MIT    Iris    201       40.2
17      Bob   Stanford  Tokoyo    202       40.4
14  Charlie    Harvard  London    304       60.8
33    David       Yale   Spain    403       80.6
12      Eve  Princeton   Paris    205       41.0