<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.DataFrame({'team':['A','A','A','A','B','B','B','B'],
                     'points':[10,10,12,12,15,17,20,20],
                     'assist':[5,5,7,9,12,9,6,6]})

In [6]:
data

  team  points  assist
0    A      10       5
1    A      10       5
2    A      12       7
3    A      12       9
4    B      15      12
5    B      17       9
6    B      20       6
7    B      20       6

In [7]:
data[data.duplicated()]

  team  points  assist
1    A      10       5
7    B      20       6

In [9]:
#Boolean
data.duplicated()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [10]:
data[data.duplicated('team')]

  team  points  assist
1    A      10       5
2    A      12       7
3    A      12       9
5    B      17       9
6    B      20       6
7    B      20       6

In [12]:
data[data.duplicated(['team','points'])]

  team  points  assist
1    A      10       5
3    A      12       9
7    B      20       6

In [13]:
data.drop_duplicates()

  team  points  assist
0    A      10       5
2    A      12       7
3    A      12       9
4    B      15      12
5    B      17       9
6    B      20       6

In [14]:
data.drop_duplicates('team')

  team  points  assist
0    A      10       5
4    B      15      12

In [15]:
data.drop_duplicates(['team','points'])

  team  points  assist
0    A      10       5
2    A      12       7
4    B      15      12
5    B      17       9
6    B      20       6

In [16]:
data.drop_duplicates(['team','points','assist'])

  team  points  assist
0    A      10       5
2    A      12       7
3    A      12       9
4    B      15      12
5    B      17       9
6    B      20       6