<a href="https://colab.research.google.com/github/salgudekomal945-ops/my-colab-work/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
names = pd.DataFrame({'Name':['Tom','Jack','Steve','Ricky','Sam','Will','Root']})
ages = pd.DataFrame({'Age':[28,34,29,42,17,17,45]})

In [3]:
names

    Name
0    Tom
1   Jack
2  Steve
3  Ricky
4    Sam
5   Will
6   Root

In [4]:
ages

   Age
0   28
1   34
2   29
3   42
4   17
5   17
6   45

In [5]:
names2 = pd.DataFrame({'Name':['Joe','Pope','Buttler','Ben','James','Cook']})

In [12]:
data = pd.concat([names,ages], axis=1) #Concatenation
display(data)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42
4    Sam   17
5   Will   17
6   Root   45

In [9]:
pd.concat([names,names2]).reset_index()   #Concatenation

    index     Name
0       0      Tom
1       1     Jack
2       2    Steve
3       3    Ricky
4       4      Sam
5       5     Will
6       6     Root
7       0      Joe
8       1     Pope
9       2  Buttler
10      3      Ben
11      4    James
12      5     Cook

In [15]:
display(data['Name'])
data.loc[1,'Age']

0      Tom
1     Jack
2    Steve
3    Ricky
4      Sam
5     Will
6     Root
Name: Name, dtype: object

np.int64(34)

In [16]:
#Series in pandas
series = pd.Series([1,2,7,8,5])
print(series)

0    1
1    2
2    7
3    8
4    5
dtype: int64

In [17]:
#Series with index
series = pd.Series([1,2,7,8,5], index=['a','b','c','d','e'])
print(series)

a    1
b    2
c    7
d    8
e    5
dtype: int64

In [19]:
#Accessing Series element
print(series["a"])
print(series["c"])

1
7

In [20]:
#DataFrame method on list
data = pd.DataFrame([1,2,3,4,5])
print(data)

   0
0  1
1  2
2  3
3  4
4  5

In [35]:
#DataFrmae using Dictionary
data = pd.DataFrame({'Name':['Tom','Jack','Steve','Ricky','Sam','Will','Root'],
                  'Age':[28,34,29,42,17,17,43]  },index = ['C1','C2','C3','C4','C5','C6','C7'])
data.head(7)

     Name  Age
C1    Tom   28
C2   Jack   34
C3  Steve   29
C4  Ricky   42
C5    Sam   17
C6   Will   17
C7   Root   43

In [34]:
#Column selection
data["Name"]
#data["Age"]

C1      Tom
C2     Jack
C3    Steve
C4    Ricky
C5      Sam
C6     Will
C7     Root
Name: Name, dtype: object

In [42]:
#Row selection
data.loc['C1','Name']
data.iloc[5,0]

'Will'